//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
	using Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class WarehouseController
	{
		public virtual CartController CartController
		{
			get;
			set;
		}

		public virtual Warehouse Warehouse
		{
			get;
			set;
		}

	}
}

