//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Board
	{
        public Dictionary<string, Track> Tracks;

        public Board()
        {
            Tracks = new Dictionary<string, Track>();

            Tracks["0,0"] = new Track();
            Tracks["1,0"] = new Track();
            Tracks["2,0"] = new Track();
            Tracks["3,0"] = new Track();
            Tracks["4,0"] = new Track();
            Tracks["5,0"] = new Track();
            Tracks["6,0"] = new Track();
            Tracks["7,0"] = new Track();
            Tracks["8,0"] = new Track();
            Tracks["9,0"] = new Track();
            Tracks["10,0"] = new Track();
            Tracks["11,0"] = new Track();
            Tracks["12,0"] = new Track();
            Tracks["13,0"] = new Track();
        }

		public virtual IEnumerable<Track> Track
		{
			get;
			set;
		}

		public virtual Player Player
		{
			get;
			set;
		}

		public virtual IEnumerable<Ship> Ship
		{
			get;
			set;
		}

		public virtual IEnumerable<Cart> Cart
		{
			get;
			set;
		}

		public virtual IEnumerable<Warehouse> Warehouse
		{
			get;
			set;
		}

		public virtual DockTrack DockTrack
		{
			get;
			set;
		}

		public virtual EndTrack EndTrack
		{
			get;
			set;
		}

		public virtual SwitchTrack SwitchTrack
		{
			get;
			set;
		}

		public virtual YardTrack YardTrack
		{
			get;
			set;
		}

		public virtual IEnumerable<SeaRoute> SeaRoute
		{
			get;
			set;
		}

	}
}

