//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
    using Ontwerp_v2._0Lib.Model;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

	public class CurvedTrack : Track
	{
        public CurvedTrack(Direction facingFrom, Direction facingTo)
            : base(facingTo)
        {
            FacingFrom = facingFrom;
            FacingTo = facingTo;
        }

        public Direction FacingTo
        {
            get;
            set;
        }

        public Direction FacingFrom
        {
            get;
            set;
        }
	}
}

