//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
    using Goudkoorts.Model.Track;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

	public class SwitchTrack : Track
	{
        public SwitchTrack(Direction facingFrom, Direction faceingTo)
        {
            FacingFrom = facingFrom;
            FactingTo = faceingTo;
        }

        public Direction FacingFrom
        {
            get;
            private set;
        }
        public Direction FactingTo
        {
            get;
            set;
        }
	}
}

