//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Track
	{
		public Cart Cart
		{
			get;
			set;
		}

        public Track NextTrack
        {
            get;
            set;
        }

	}
}

