//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Controller
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
	using View;

	public class StartController
	{
		public virtual StartView StartView
		{
			get;
			set;
		}

	}
}

