//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Board
	{
		public virtual IEnumerable<Track> Track
		{
			get;
			set;
		}

		public virtual Player Player
		{
			get;
			set;
		}

		public virtual IEnumerable<Ship> Ship
		{
			get;
			set;
		}

		public virtual IEnumerable<Cart> Cart
		{
			get;
			set;
		}

		public virtual IEnumerable<Warehouse> Warehouse
		{
			get;
			set;
		}

		public virtual DockTrack DockTrack
		{
			get;
			set;
		}

		public virtual EndTrack EndTrack
		{
			get;
			set;
		}

		public virtual SwitchTrack SwitchTrack
		{
			get;
			set;
		}

		public virtual YardTrack YardTrack
		{
			get;
			set;
		}

		public virtual IEnumerable<SeaRoute> SeaRoute
		{
			get;
			set;
		}

	}
}

