//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace View
{
    using Model;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

	public class BoardView
	{
        public Board Board;
        public BoardView(Board board)
        {
            Board = board;
        }

        public void Show()
        {
            Console.WriteLine("BoardView.Show()");
            //TODO

            for (int x = 0; ; x++)
            {
                for (int y = 0; ; y++)
                {
                    Track track = Board.Tracks[x + "," + y];

                    Console.Write("-");
                    if (track is Track) {
                        
                    }
                }
            }
        }
	}
}

